version: 2.1
jobs:
  compile:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           git config --global user.name "ramadhannangga"
           git config --global user.email "ramadhananggayudhanto@gmail.com"
           git config --global color.ui false
           git clone --depth=1 https://github.com/${CIRCLE_PROJECT_USERNAME}/CircleCI -b BUILD-Q
           bash compile.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
